version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/root/logs
      - ./config.json:/root/config.json:ro
    environment:
      - GIN_MODE=release
    restart: unless-stopped

volumes:
  logs: