version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./requests.log:/root/requests.log
      - ./config.json:/root/config.json
    environment:
      - GIN_MODE=release
    restart: unless-stopped

volumes:
  logs: